name: Release

on:
  release:
    types: [published, edited]

jobs:

  actions-tagger:
    name: Action Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish Tag
        uses: Actions-R-Us/actions-tagger@v2
